version: "3.6"

services:
#  flyway:
#    image: flyway/flyway:latest
#    command: -url=jdbc:postgresql://db/spring_security?allowPublicKeyRetrieval=true&useSSL=false -schemas=spring_security -user=root -password=password -connectRetries=60 migrate
#    volumes:
#      - ./src/main/resources/db/migration:/flyway/postgresql
#    depends_on:
#      - db
#    networks:
#      - backend

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=spring_security
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - spring3-security:/var/lib/postgresql
    networks:
      - backend

volumes:
  spring3-security:
    driver: local

networks:
  backend: